export const defaultParams = {
  mode: "readability",
  contrast: 1.25,
  brightness: 1,
  gamma: 1,
  sharpen: 0.6,
  grayscale: false,
  threshold_enabled: false,
  threshold_value: 168,
  adaptive_threshold: false,
  denoise: 0.4,
  edge_boost: 0.5,
  line_thicken: 0,
  morph_close: 0,
  invert: false,
  rotation: 0,
  crop_enabled: false,
  auto_crop: false,
  crop_box: null,
  preview_dpi: 150,
  export_dpi: 300,
};

export const presets = {
  "Blasser Bestandsplan": {
    contrast: 1.65,
    brightness: 1.06,
    gamma: 0.86,
    sharpen: 0.8,
    grayscale: false,
    threshold_enabled: false,
    adaptive_threshold: false,
    denoise: 0.5,
    edge_boost: 0.8,
    line_thicken: 0,
    morph_close: 0,
  },
  "Maßketten lesbarer": {
    contrast: 1.75,
    brightness: 1,
    gamma: 0.82,
    sharpen: 1.2,
    grayscale: false,
    threshold_enabled: false,
    adaptive_threshold: false,
    denoise: 0.4,
    edge_boost: 1.2,
    line_thicken: 1,
    morph_close: 0,
  },
  "Dünne Linien verstärken": {
    contrast: 1.5,
    brightness: 1,
    gamma: 0.92,
    sharpen: 1,
    grayscale: false,
    threshold_enabled: false,
    adaptive_threshold: false,
    denoise: 0.5,
    edge_boost: 1,
    line_thicken: 2,
    morph_close: 1,
  },
  "Schwarz-Weiß CAD-Vorlage": {
    mode: "cad",
    contrast: 1.9,
    brightness: 1.04,
    gamma: 0.95,
    sharpen: 0.7,
    grayscale: true,
    threshold_enabled: false,
    adaptive_threshold: true,
    denoise: 0.7,
    edge_boost: 0.5,
    line_thicken: 1,
    morph_close: 1,
  },
  "Schonende Verbesserung": {
    contrast: 1.25,
    brightness: 1.02,
    gamma: 0.95,
    sharpen: 0.4,
    grayscale: false,
    threshold_enabled: false,
    adaptive_threshold: false,
    denoise: 0.3,
    edge_boost: 0.3,
    line_thicken: 0,
    morph_close: 0,
  },
  "Orthofoto klarer": {
    mode: "image",
    contrast: 1.18,
    brightness: 1.02,
    gamma: 0.96,
    sharpen: 0.9,
    grayscale: false,
    threshold_enabled: false,
    adaptive_threshold: false,
    denoise: 0.25,
    edge_boost: 0.15,
    line_thicken: 0,
    morph_close: 0,
  },
};

export const modes = [
  { id: "readability", label: "Lesbarkeit" },
  { id: "cad", label: "CAD-Hinterlegung" },
  { id: "detail", label: "Detail" },
  { id: "image", label: "Bild/Orthofoto" },
  { id: "batch", label: "Batch" },
];
